### ISSUE TITLE
f = fst.Fst().  error

### ISSUE THREAD

**Issue by Alex-Songs** [jpuigcerver/openfst-python#5]
>>> import openfst_python as fst
>>> f = fst.Fst()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pywrapfst.pyx", line 1617, in pywrapfst.Fst.__init__
AttributeError: 'pywrapfst.Fst' object has no attribute '_class__'

**Comment by jpuigcerver** [comment]
The code works with OpenFst 1.7.9. Are you using that version?

**Comment by ianlini** [comment]
@jpuigcerver This seems like a duplicate of #2, and [you said](https://github.com/jpuigcerver/openfst-python/issues/2#issuecomment-709994199) that:

> Yes. The Python interface for OpenFst has been broken at least since version 1.7.1. Last time I checked, 1.7.9 was still broken. This library uses wraps that interface, so until they fix it, there's not much I can do.
>
> You can switch to the 1.6.9 branch and that should be fine.
